import Anthropic from '@anthropic-ai/sdk';

export const MODEL_NAME = import.meta.env.VITE_LLM_MODEL || 'claude-sonnet-5';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
// Deliberately the publishable key, not VITE_SUPABASE_ANON_KEY: the proxy
// function's ambient SUPABASE_ANON_KEY (see anthropic-proxy/index.ts) holds
// the project's new-format publishable key, and VITE_SUPABASE_ANON_KEY is
// still the legacy JWT format — the two no longer match. Both vars are
// auto-generated by the Supabase-Vercel integration.
const supabasePublishableKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!supabaseUrl || !supabasePublishableKey) {
  console.error(
    'Missing Supabase env vars no arquivo .env — needed both for Supabase ' +
      'itself and for reaching the Claude proxy function below.'
  );
}

// The Anthropic API key never reaches the browser. This client is pointed
// at a Supabase Edge Function (supabase/functions/anthropic-proxy) that
// injects the real key server-side and forwards the request to
// api.anthropic.com — the `apiKey` below is never sent anywhere that
// matters, it just satisfies the SDK's constructor.
export const client = new Anthropic({
  apiKey: 'unused-key-lives-server-side',
  baseURL: `${supabaseUrl}/functions/v1/anthropic-proxy`,
  dangerouslyAllowBrowser: true,
  defaultHeaders: {
    Authorization: `Bearer ${supabasePublishableKey}`,
  },
});

// Persona/instruction strings live in a browser-agnostic module so the
// Telegram bot Edge Function (Deno) can share them. Re-exported here to keep
// existing import sites (./client) working unchanged.
export { TONE_INSTRUCTION, SYSTEM_INSTRUCTION } from './prompts';
